-- AlterTable
ALTER TABLE "Exam" ALTER COLUMN "starttime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "timelimit" SET DEFAULT '02:00',
ALTER COLUMN "timelimit" SET DATA TYPE TEXT,
ALTER COLUMN "jointime" SET DEFAULT '00:15',
ALTER COLUMN "jointime" SET DATA TYPE TEXT;
