name: Backend Deploy

on:
  push:
    branches: [main]
    tags:
      - "v*"
    paths:
      - "backend/**"

env:
  BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
  DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}
jobs:





  build-backend:
  
    runs-on: ubuntu-latest
    outputs:
      imagetag: ${{ steps.image_tag.outputs.imagetag }}

    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tag, labels)
        id: meta
        uses: docker/metadata-action@v5.9.0
        with:
          images: ${{env.BACKEND_IMAGE}}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy backend (first tag only)
        id: image_tag
        run: |
          # Get first tag from metadata (split by newline)
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tag-names }}" | head -n1)
          if [ -z "$FIRST_TAG" ]; then
            echo "No tag found, exiting."
            exit 1
          fi
          echo "Deploying tag: $FIRST_TAG"
          echo "imagetag=$FIRST_TAG" >> $GITHUB_OUTPUT

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: check image tag
        run: |
          echo ${{ needs.build-backend.outputs.imagetag }}
          echo "Deploying imagetag=${{env.BACKEND_IMAGE}}:${{ needs.build-backend.outputs.imagetag }}"

      - name: SSH into host
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: BACKEND_IMAGE,DOCKER_NETWORK
          script: |
            # Pull new image as green
            echo "$BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}"

            sudo docker pull $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}

            LIVE=$(grep -oP 'default\s+\Kbackend_(blue|green)' /etc/nginx/conf.d/app.conf)
            echo "LIVE IS: $LIVE"

            if [ "$LIVE" = "backend_blue" ]; then
              TARGET="backend_green"
              PORT=3002
            else
              TARGET="backend_blue"
              PORT=3001
            fi


            echo "Deploy TARGET: $TARGET on PORT: $PORT"

            sudo docker run -d \
              --name $TARGET \
              --network $DOCKER_NETWORK \
              -p $PORT:3000 \
              $BACKEND_IMAGE:${{ needs.build-backend.outputs.imagetag }}

            # Health check loop (max 30s)
            for i in {1..30}; do
              if curl -sSf http://localhost:$PORT/health; then break; fi;
              sleep 1;
            done

            echo "Switch Nginx upstream $LIVE to $TARGET"
            sudo sed -i "s/default $LIVE;/default $TARGET;/" /etc/nginx/conf.d/app.conf
            echo "nginx reloading"

            sudo nginx -s reload
            echo "sleeping for 100s"

            sleep 60

            sudo nginx -t && sudo nginx -s reload

            echo "removing old and in active contanier"
            sudo docker stop $LIVE || true 
            sudo docker rm $LIVE || true

            echo "Cleanup unused Docker images ✔️"
            sudo docker system prune -f